import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Terms() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Terms of Service - Wordplay</title>
      </Head>
      <main style={{ maxWidth: 700, padding: "40px 20px", lineHeight: 1.8 }}>
        <h1>Terms of Service</h1>
        <p>
          <strong>Last updated:</strong> March 2026
        </p>

        <h2>Acceptance of Terms</h2>
        <p>
          By accessing or using Wordplay ("the Service"), you agree to be bound
          by these Terms of Service. If you do not agree to these terms, please
          do not use the Service.
        </p>

        <h2>Description of Service</h2>
        <p>
          Wordplay is a creative writing exercise generator that uses AI to
          create personalized writing prompts based on user-selected parameters.
          The Service is provided "as is" and "as available."
        </p>

        <h2>User Accounts</h2>
        <p>
          You may use Wordplay without an account. If you create an account, you
          are responsible for maintaining the security of your login credentials.
          You must provide accurate information when creating an account.
        </p>

        <h2>Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>
            Use the Service for any unlawful purpose or to generate harmful
            content
          </li>
          <li>
            Attempt to access, tamper with, or use non-public areas of the
            Service
          </li>
          <li>
            Send automated requests that could overload or impair the Service
          </li>
          <li>
            Attempt to reverse engineer any aspect of the Service
          </li>
        </ul>

        <h2>Intellectual Property</h2>
        <p>
          Writing prompts generated by the Service are provided for your
          personal creative use. You retain full ownership of any stories,
          content, or works you create using prompts from Wordplay.
        </p>

        <h2>AI-Generated Content</h2>
        <p>
          Writing prompts are generated using artificial intelligence. While we
          strive for quality, we do not guarantee that generated content will be
          free from errors, biases, or inappropriate material. Use your
          judgment when working with AI-generated prompts.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Wordplay and its creators
          shall not be liable for any indirect, incidental, special,
          consequential, or punitive damages arising from your use of the
          Service.
        </p>

        <h2>Service Availability</h2>
        <p>
          We do not guarantee uninterrupted access to the Service. We may modify
          or discontinue the Service at any time without notice.
        </p>

        <h2>Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. Continued use
          of the Service after changes constitutes acceptance of the updated
          Terms.
        </p>

        <h2>Contact</h2>
        <p>
          For questions about these Terms, contact us at{" "}
          <a href="mailto:ebonyhargro@gmail.com">ebonyhargro@gmail.com</a>.
        </p>

        <p style={{ marginTop: 40 }}>
          <a href="/">Back to Wordplay</a>
        </p>
      </main>
    </div>
  );
}
